### ISSUE TITLE
how to integrate Databucket with AD to use OAuthLogin?

### ISSUE THREAD

**Issue by sfrubio** [databucket/databucket-server#119]
I'm trying to configure Databucket to authenticate through Keycloak.
To do this, I've included the following Spring Security configuration in application.yaml:
```yaml
spring:
   security:
      oauth2:
         client:
            registration:
               keycloak:
                  provider: QA
                  authorization-grant-type: authorization_code
                  client-id: databucket
                  client-secret: my-client-secret
               provider:
                  QA:
                     issuer-uri: http://localhost:8180/realms/QA
                     user-info-uri: http://localhost:8180/realms/QA/protocol/openid-connect/userinfo
                     jwk-set-uri: http://localhost:8180/realms/QA/protocol/openid-connect/certs
                     authorization-uri: http://localhost:8180/realms/QA/protocol/openid-connect/auth
                     token-uri: http://localhost:8180/realms/QA/protocol/openid-connect/token
```

With this configuration, I was expected to get the Keycloak login form.
Checking the frontend source code, I've found the following code in [AuthPage.jsx]():
```jsx
            <Paper elevation={3}>
                <LoginFormComponent/>
                {authOptions.length > 0 && <Divider variant="middle"/>}
                {authOptions.length > 0 && <OauthLoginComponent
                    authOptions={authOptions}/>}
```
This code expect to get the auth options through a request to `getBaseUrl("auth/auth-options")`, but this request returns a web page with HTTP 404.

Do you have any example on how to integrate Databucket with AD to use OAuthLogin, just to check what I'm doing wrong? Or there is any path I should follow to procceed with OAuth login?
